apiVersion: v1
kind: ServiceAccount
metadata:
  name: rollout-helper
  namespace: snappcloud-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: snappcloud-rollout-helper
subjects:
- kind: ServiceAccount
  name: rollout-helper
  namespace: snappcloud-tools
roleRef:
  kind: ClusterRole
  name: system:node-reader # allow Get/List/Watch on Nodes
  apiGroup: rbac.authorization.k8s.io